name: CI

on:

  pull_request:
    branches: [ develop ]

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npx jest --ci --coverage

